apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: zookeeper
  labels:
    service: zookeeper
    app: zookeeper
spec:
  ports:
    - name: peer
      port: 2888
    - name: leader-election
      port: 3888
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-client
  labels:
    service: zookeeper
    app: zookeeper
spec:
  ports:
  - name: client
    port: 2181
  - name: commands
    port: 8080
  selector:
    app: zookeeper
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper
      annotations:
    spec:
      containers:
      - name: zookeeper
        image: dstritzke/zookeeper:3.5
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader-election
        - containerPort: 8080
          name: commands
        volumeMounts:
        - name: data
          mountPath: /data
        - name: datalog
          mountPath: /datalog
        readinessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "/zkOk.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 5
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: datalog
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi